### ISSUE TITLE
How to build with purge ?

### ISSUE THREAD

**Issue by pasdut** [DrBuchkov/lein-tailwind#1]
Hi,

How can we build tailwind for production ?  
From the tailwind doc I should set  NODE_ENV to production.  But I don't have a clue how to do that from within the lein-tailwind plugin.

I currently solved this by creating 2 configs : _tailwind.config.js_ and _tailwind.prod.config.js_ (the latter has purge : enabled: true)
But of course this is not ideal because I now have to maintain 2 config files...

tailwind.prod.config.js :
```
module.exports = {
  purge: {
	  enabled: true,
	  content: [
			'/src/**/*.cljs',
			'/src/**/*.clj'  ]  },

```

And in my project.clj I switch to the production in the profile section 

```
:profiles
  {:dev   {}
   :prod 
   {:tailwind {
            :tailwind-config  "tailwind.prod.config.js"  }  }
```

**Comment by pasdut** [comment]
The solution couldn't be more easier.

For dev you build as follow:
`$ lein tailwind build`

For production:
`$ NODE_ENV=production lein tailwind build`

And for windows probably  (not tested)
`> set NODE_ENV=production&&lein tailwind build`
**No spaces** before and after `&&` !

**Comment by conjurernix** [comment]
I'm sorry for the late reply. This lein plug in doesn't give extra support for different configurations as you can just do it with setting NODE_ENV in the terminal as you did or with other leiningen trickery.

Edit: Spelling.

**Comment by conjurernix** [comment]
Another note, Since purge is basically using PurgeCSS, I don't think purge will work when you provide your .clj and .cljs files. Maybe try doing it to the compiled files of cljs.

**Comment by pasdut** [comment]
Hi Nikolas,

No problem at all. I'm new to lein (and clojure) and I just couldn't find out how to do it.

Also thanks for the remark on PureCSS. I just tested the tailwind size with and without purge and the difference is huge, so I thought it was working 😂.

Kind regards,
Pascal

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by conjurernix** [comment]
That's great actually. I was skeptical that it would trim anything but looks like the tooling is smart enough.
